spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/william1638/demo/
          username: william1638
          password: 62010422wenzhou
          search-paths: spring_cloud_in_action/config-repo

server:
  port: 7001
